INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE, JOB) VALUES ('Foubert', 'Sebastien', '1980-07-31', 'DEV');
INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE, JOB) VALUES ('Employee 1', 'Employee 1', '1990-01-01', 'DEV');
INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE, JOB) VALUES ('Employee 2', 'Employee 2', '1990-01-01', 'ARCHITECT');
INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE, JOB) VALUES ('Employee 3', 'Employee 3', '1990-01-01', 'ARCHITECT');
INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE, JOB) VALUES ('Employee 4', 'Employee 4', '1990-01-01', 'CEO');
INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE, JOB) VALUES ('Employee 5', 'Employee 5', '1990-01-01', 'TECHLEAD');
INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE, JOB) VALUES ('Employee 6', 'Employee 6', '1990-01-01', 'TECHLEAD');
INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE, JOB) VALUES ('Employee 7', 'Employee 7', '1990-01-01', 'TECHLEAD');