INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE) VALUES ('Foubert', 'Sebastien', '1980-07-31');
INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE) VALUES ('Employee 1', 'Employee 1', '1990-01-01');
INSERT INTO EMPLOYEE(LASTNAME, FIRSTNAME, BIRTHDATE) VALUES ('Employee 2', 'Employee 2', '1990-01-01');